# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_utility <- function(core_no, seed, times) {
    .Call('_aphids_get_utility', PACKAGE = 'aphids', core_no, seed, times)
}

